name: Build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:

env:
  BUILD_DIR: build
  CTEST_OUTPUT_ON_FAILURE: 1
  GITHUB_HUNTER_USERNAME: ${{ secrets.HUNTER_USERNAME }}
  GITHUB_HUNTER_TOKEN: ${{ secrets.HUNTER_TOKEN }}
  CACHE_VERSION: v01
  CACHE_PATHS: |
    ~/.ccache
    ~/.hunter

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ github.job }}-${{ env.CACHE_VERSION }}
      - name: build
        run: ./scripts/build.sh

  Linux:
    strategy:
      fail-fast: false
      matrix:
        options:
          - name: "Linux: gcc"
            run: ./scripts/build.sh -DCMAKE_CXX_COMPILER=g++
          - name: "Linux: clang"
            run: ./scripts/build.sh -DCMAKE_CXX_COMPILER=clang++
    name: "${{ matrix.options.name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ github.job }}-${{ matrix.options.name }}-${{ env.CACHE_VERSION }}
      - name: "${{ matrix.options.name }}"
        run: "${{ matrix.options.run }}"

  clang-tidy:
    name: "Linux: clang-tidy"
    runs-on: ubuntu-latest
    container: qdrvm/kagome-dev@sha256:2d70246c32418a3dd45c246d3f5c2dd99bdafde145b903271849affe476c4cfc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ github.job }}-${{ env.CACHE_VERSION }}
      - name: clang-tidy
        env:
          BUILD_TARGET: all
        run: |
          ./scripts/build.sh
          ./scripts/generate_clang_tidy_diff.sh
