name: Build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:

env:
  BUILD_DIR: build
  CTEST_OUTPUT_ON_FAILURE: 1
  GITHUB_HUNTER_USERNAME: ${{ secrets.HUNTER_USERNAME }}
  GITHUB_HUNTER_TOKEN: ${{ secrets.HUNTER_TOKEN }}
  CACHE_VERSION: v01
  CACHE_PATHS: |
    ~/.ccache
    ~/.hunter

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ github.job }}-${{ env.CACHE_VERSION }}
      - name: build
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
        run: ./scripts/build.sh

  Windows-MSVC:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ github.job }}-${{ env.CACHE_VERSION }}
      - name: build on msvc
        run: bash ./scripts/build.sh
